[project]
name = "tscrb"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mistralai>=1.9.11",
    "openai>=2.8.1",
    "typer>=0.20.0",
]

[project.scripts]
tscrb = "tscrb.cli:app"

